- README.md
- modules/default.nix
Add usage examples for the module public API.
Add documentation for the `services.flatpak.remotes` option.
> default: add example for flake module options.

- README.md
- modules/default.nix
- modules/home-manager.nix
- modules/installer.nix
- modules/nixos.nix
Closes #4.
Adds the capability to update installed applications at activation, and periodically.
Automated updates are not enable by default, so each system activation is idempotent.
Set
```nix
services.flatpak.update.onActivation = true;
```
to enable updates at system activation. The default is `false`
so that repeated invocations of `nixos-rebuild switch` are idempotent. Applications 
pinned to a specific commit hash will not be updated.
Periodic updates can be enabled  by setting:
```nix
services.flatpak.update = {
auto = {
enable = true;
onCalendar = "weekly"; # Default value
};
};
```
Auto updates trigger on system activation.
> Add options to update installed applications.

- README.md
Add a known issues section.
Inform of infinite recursion import issue reported in #25.
> Infinite recursion import

- modules/home-manager.nix
- modules/installer.nix
- modules/options.nix
First of all thanks for creating this module! Convergent mode feels like the right the approach of combining Flatpak and NixOS to me, so I'm happy this exists.
Before this PR, there was an issue of packages being overridden on activation of the module, meaning if packages were installed outside of this module, they would get uninstalled on the next activation, and only the packages declared in this module would be left. This felt like a design flaw to me so I decided to fix it, I hope you agree and that this was not an intentional design choice.
This PR introduces a state file that keeps track of the module's modifications, so that they can be managed separately from imperatively introduced modifications. This is largely inspired by the way home manager handles [dconf …
> Only uninstall packages managed by this module

- modules/installer.nix
Fixes cat not being accessible by installer script
> installer: fix missing path to cat

- modules/installer.nix
Check that `OLD_STATE` has been populated before attempting to diff it with `NEW_STATE`,
when determining what packages to uninstall.
Fixes the following error:
```
jq: error (at <unknown>): null (null) and array (["im.riot.R...) cannot be subtracted
```
This is the case on newly provisioned instances, with no flatpaks previously installed (either managed by `nix-flatpak` or unmanaged).
> installer: don't uninstall on empty OLD_STATE.

- modules/home-manager.nix
- modules/installer.nix
- modules/options.nix
- modules/overrides.jq
This PR builds on top of PR #23, as it relies on a similar strategy to separately manage the declarative and imperative states. If/when that PR is merged I'll rebase this PR to only include the relevant commit.
This wasn't a trivial task and was mainly accomplished using jq, the logic of which has been separated into the `
modules/overrides.jq` file. The installer simply provides the needed values to it by looping over previously and currently managed overrides, then reading their active (the actual Flatpak overrides files), old and new states (the files introduced in #23) from the respective files.
The actual logic to determine a value for an overrides entry is quite simple:
- If the new value is a string, simply override the active/old value
- If the value is an array, perform the …
> Add overrides management

- testing-base/README.md
- testing-base/common.nix
- testing-base/configuration.nix
- testing-base/flake.lock
- testing-base/flake.nix
Add a base 23.11 nixos system with Gnome, GDM
and nix-flatpak installed.
> Add testing-base.

- modules/installer.nix
This is a follow up on https://github.com/gmodena/nix-flatpak/pull/24#issuecomment-1917639479. I looked into it and turns out I actually already implemented it correctly for overrides, using fallback values in `jq` (i.e. `null // []` and `null // {}`), so that bug shouldn't occur there. But I think it's also worth implementing it that way for uninstalls, as it's a bit more resilient than comparing old state to an empty object. F.e. if the old state is not an empty object, but is missing the "packages" key for some reason, this would still work (as opposed to the current solution). It's not really necessary right now, but it might avoid bugs in the future.
> installer: add fallback values to uninstall jq command to avoid bugs

- README.md
Document how remote management is implemented.
Add a reference to lib.`mkOptionDefault`, that allows to merge a config with its default values.
Addresses concerns raised in #32
> readme: improve remotes config doc.

- modules/installer.nix
Fixes mkdir, cat and ln not being accessible
by the installer script.
Regression introduced by #39
> installer: fix path to coreutils commands.

- modules/home-manager.nix
- modules/nixos.nix
Start the `flatpak-managed-install` service after `multi-user.target`.
This should ensure that network interfaces are up, and connectivity has been established.
Fixes #30
> systemd: start unit after multi-user.target

- CONTRIBUTORS.md
- README.md
- modules/options.nix
Two issue existed with the options documentation that caused build failures when `documentation.nixos.enable` and `documentation.nixos.includeAllModules` are set to `true`.
The first issue was that `mkDoc` was used rather than `lib.mdDoc` in two locations. `mkDoc` isn't valid, so I replaced both instances of it with `lib.mdDoc`.
The second issue was that not all options of `nix-flatpak` had descriptions. This also causes a build failure.
In addition to fixing the two issues above that cause build failures, I also:
* Fixed a typo in `README.md`.
* Made minor additions and corrections to existing option docs.
* Added spaces so option docs would be rendered correctly:
* The way multi-line string blocks work in Nix is that the indent is determined by the line that's indented the least.
* Thus …
> Bug | Option Documents Break Nix Build

- modules/home-manager.nix
- modules/installer.nix
- modules/nixos.nix
- modules/options.nix
- testing-base/flake.lock
- testing-base/flatpak.nix
Remotes removed from nix-flatpak config declaration will be uninstalled at system activation.
Add the capability to delete unmanged remotes at system activation.
Rename `uninstallUnmanagedPackages` to a more generic `uninstallUnmanaged`.
Trigger warning when deprecated options are set.
Initial work for  #32
> installer: manage remotes state.

- modules/options.nix
Coerce the `null` value to `false` when initializing the value of `uninstallUnmanaged` from the `uninstallUnmanagedPackages` option default value.
Fixes issue #61.
> options: fix uninstallUnmanaged default value.

- modules/home-manager.nix
- modules/nixos.nix
- modules/options.nix
Fix "uninstallUnamanged" typo to "uninstallUnmanaged" in doc and error strings.
Bug: #73
> modules: fix uninstallUnmanaged typo.

- testing-base/common.nix
- testing-base/flatpak.nix
Ensure that the flatpak binary will be available
also when building a VM variant that loads
nix-flatpak as an home-manager module.
> testing-base: enable flatpak in vm base config.

- .github/workflows/test.yml
- README.md
- modules/installer.nix
- modules/options.nix
- modules/ref.nix
- tests/fixtures/package.flatpakref
- tests/ref-test.nix
**This is a WIP**.
Issue #78 
Adds support for installing application from a flatpakref uri.
When installing from a flatpakref,  and packages will tracked in the gcroot state files:
1. a package will be stored, with `appId` and `origin` set to the flatpakref's `Name` and `SuggestRemoteName` respectively.
2. a remote with be stored labelled with  `SuggestRemoteName`. 
This should enable compatibility with state management APIs.
Workflow: 
1. declare a flatpakref package.
2. on activation, the package and its remote are installed.
3. remove the flatpakref declaration.
4. on activation, the package and it's remote are removed.
```
services.flatpak.remotes = lib.mkOptionDefault [{
name = "flathub-beta";
location = "https://flathub.org/beta-repo/flathub-beta.flatpakrepo";
}; …
```
> installer: add support for flatpakref.

- modules/installer.nix
Remove remotes even if refs are installed. This can occur in cases of manual installation of remotes and packages. If the user sets uninstallUnmanagedState = true, forcefully remove any remaining dangling dependencies.
Follow up to #78
> installer: forcefully delete remotes when managing state.

- README.md
- modules/installer.nix
- modules/ref.nix
- modules/remotes.nix
- tests/ref-test.nix
When a flatpakref file does not provide a SuggestRemoteName key, create an origin from the Name field.
This change implements the algorithm found in flatpak's create_origin_remote_config() function.
Remove the option of setting an origin label in packageOption. This option was poorly documented, and its default behavior ( labeling as "flathub" if no origin was set) would break system activation.
Fixes #90
> ref: fix remote origin management

- modules/options.nix
nixpkgs will soon remove lib.mdDoc, stating all option descriptions are in markdown by default, in fact, currently on nixpkgs-unstable, it fails to build. this PR is a simple removal of all mentions. the provided test suite passes, at least on x86_64-linux nixos.
> delete all uses of removed lib.mdDoc

- .github/workflows/tag-latest.yml
Drop the use of Github action to avoid
granting write access to third parties.
> github: manually extract and tag latest tag.

- README.md
Document the use of `latest` tag to automatically track the most recent release.
Suggested in #113
> README: document latest tag

- modules/installer.nix
- modules/options.nix
This PR introduces the capability to automatically uninstall unused packages by running `flatpak uninstall --unused` during activation or a scheduled update execution.
A new `services.flatpak.uninstallUnused` option is added, defaulting to `false`. This option is independent of `services.flatpak.uninstallUnmanaged`.
However, enabling `services.flatpak.uninstallUnmanaged` will automatically enable `services.flatpak.uninstallUnused`.
Closed #96
> options: add uninstallUnused option

- modules/home-manager.nix
- modules/nixos.nix
- modules/options.nix
I just implemented part of the changes we were discussing in #45.
I figured out that the stuff I was saying on the `WantedBy=` option does not make sense, since we need the service to start to have flatpaks installed and making the `Wantedby=` option empty prevents that, even on rebuilds. However, I only used the setup in testing-base/ to verify this.
I still wanted to have slightly better resilience to network failures, and the current solution goes hand in hand with the need of having the service started on each activation. 
My take on the problem makes the `flatpak-managed-install.service` automatically restart on failure with a customizable delay. The user has also the option to enable an exponential backoff strategy, with a customizable number of steps and maximum restart delay.
This …
> Enable restart on failure and optionally exponential backoff

- modules/options.nix
Fixes a typo in options, and a missing semi-colon
after the block closing bracket.
Follow up to #127 for a small bug that was not caught in  code review and CI.
Tested locally in VM to confirm that the feature now works as expected.
cc @Nick1296
> restartOnFailure: fix option typo.

- modules/installer.nix
Guard against cases where a user removes an application both manually and through
configuration between activations. This code path triggers when `uninstallUnmanaged=false`,
and nix-flatpak fails to clean up inconsistencies before reaching the uninstall phase.
Don't hard fail on uninstall of packages already manually removed by the user; 
display a warning message instead.
Successful activation should then reconcile old/new state and flatpak installation.
Fixes #126
> installer: warning for manual app removal edge case

- README.md
- modules/installer.nix
- modules/state.nix
- tests/fixtures/flatpak-state.json
- tests/state-test.nix
Refactor activation logic to evaluate the system's flatpak configuration and determine whether `flatpak install` commands are required. Avoids unnecessary reinstallation and network calls during activation, improving support for "offline" environments.
Introduces a new state module to manage activation-related state.
Adds helpers to process `flatpak-state.json` with Nix expressions.
Note: For packages pinned to a specific `commit` hash, a remote query is still required to verify the reference, resulting in a network call.
Contributes to issue #110  
Informs  issues #45 #125
> installer: minimize side effects on activation

- modules/nixos.nix
Fix `mkCommonServiceConfig` argument.
Fixes #137
> nixos: rename execution context param.

- modules/flatpak/install.nix
- modules/flatpak/remotes.nix
- tests/idempotent-install-test.nix
- tests/remotes-test.nix
- tests/update-on-activation-test.nix
- tests/update-on-timer-test.nix
Checks whether packages and remotes need to be installed before executing flatpak commands.
Doing so avoid un-necessary network lookups and removes side effects from the installation process.
`nix-flatpak` tracks its state (installed packages, remotes and overrides) in a file within the nix store. This file is symlinked from a known location outside the store for easy access (e.g `$HOME/.local/state/home-manager/gcroots/flatpak-state.json `). However, this design creates a limitation: during build time, pure nix evaluation cannot access this state information because nix prohibits dereferencing symlinks outside the store.
With his PR the `nix-flatpak` state is evaluated at runtime (e.g., when executed via onActivation) by the installation script to check the following conditions for each …
> flatpak: remove network side effects on activation

- modules/common.nix
The timer used for managing automated updates was using the right service name, but pointing to the wrong unit.
> systemd: fix incorrect unit name for timer

- CONTRIBUTORS.md
Adds credits for retry-on-error logic
on systemd unit restarts introduced in PR #127.
cc / @Nick1296
> Add Nick1296 to the contributors' credits.

- flake.nix
This way we solve 2 problems:
1. Warnings and errors will be attributed to the correct file
2. importing it multiple times will not cause redefinition errors
> Fix location metadata

- modules/flatpak/install.nix
- modules/flatpak/state/compare_sha.jq
- modules/options.nix
- tests/idempotent-install-test.nix
- tests/install-from-file-test.nix
- tests/state/compare_sha-test.nix
- tests/update-on-activation-test.nix
- tests/update-on-timer-test.nix
Adds a new `bundle` option to install application
from bundle files.
Local files will require a `sha256`, as generated by `nix-prefetch-url <uri>`.
Omitting the `sha256` attribute will require
an `impure` evaluation of the flake.
The bundle we want installed is located at:
```
/home/gmodena/config/bundles/io.github.softfever.OrcaSlicer.flatpak
```
The bundle must be renamed to a valid application id format (required by `flatpak`). 
For a pure evaluation of the flake, we need to provide the SHA-256 hash of the nix-store path of the file.
This can be obtained with:
```
$ nix-prefetch-url file:///home/gmodena/config/bundles/io.github.softfever.OrcaSlicer.flatpak
path is '/nix/store/6811vgfbzlbi9m3gdidg8jfs0gfbq8g2-io.github.softfever.OrcaSlicer.flatpak' …
```
> flatpak: install from bundle fil files.

- modules/flatpak/install.nix
- tests/update-on-activation-test.nix
- tests/update-on-timer-test.nix
Remove redundant test on update triggers
and delegate the install/update command generation logic to `determineFlatpakStateChange`.
Fixes a bug that caused bundle installation to fail when auto-update was enabled.
Part of #135
> install: simplify package update logic.

- modules/home-manager.nix
Using `config.systemd.user.systemctlPath` instead of `pkgs.systemd` improves compaibility with non-NixOS installations of home-manager. In particular, this allows removing Nix's systemd from the output closure to use the host's instead.
> systemd: Use binary path from home-manager
